name: first workflow
on:
  push:

    jobs:
      job1:
        runs-on: ubuntu:latest
        steps:
          step-1:
            - name: Build
              run: echo "This is Build Stage"
          step-2:
            - name: Test
              run: echo "This is Test stage"
