name: checkout demo
on: 
  workflow_dispatch:
jobs:
  list-files-before:
    runs-on: ubuntu-latest
    steps:
      - name: list files before checkout
        run: ls -la
      - name: checkout
        uses: actions/checkout@v4
      - name: list after checkout
        run: ls -la

      - name: Git Information
        run: |
          git status
          git branch
          git log -1 --oneline
          echo "$GITHUB_REPOSITORY"
          echo "$GITHUB_WORKSPACE"
          echo "$GITHUB_RUN_ID"
          echo "$GITHUB_REF"
