name: CI
on:
  push:

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo "Starting CI workflow"

      - name: Directory
        run: pwd

      - name: List Files
        run: ls -al

      - name: Show os
        run: uname -a

      - name: CI success
        run: echo "pipeline successfull"
