name: github values
on:
  workflow_dispatch:
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Github-Information
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Username: ${{ github.actor }}"
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "RunID: ${{ github.run_id }}"
