name: Input and Env

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment Environment"
        required: true
        default: "Staging"

jobs:
  job-1:
    runs-on: ubuntu-latest

    steps:
      - name: Environment input
        run: echo "Deploying to: ${{ inputs.environment }}"
