name: inspect installed tools
on: 
  workflow_dispatch:
jobs:
  checking-installed-tools:
    runs-on: ubuntu-latest
    steps:
      - name: Git version
        run: git --version
      - name: python version
        run: python --version
      - name: Node version
        run: node --version
      - name: npm version
        run: npm --version
      - name: docker version
        run: docker --version
#Here I am going to install terraform beacuse it is not already installed unlike others
      - name: installing terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.16.5"
      - name: Terraform Version
        run: terraform --version
      - name: show env
        run: env
