name: Input and Env

"on":
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment Environment"
        required: true
        default: "Staging"
        type: string

env:
  APP_NAME: "abhi-app-v1"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Show Environment
        run: echo "Environment: ${{ inputs.environment }}"

      - name: Show Application
        run: echo "Application: $APP_NAME"

      - name: Show Deployment
        run: echo "Deploying $APP_NAME to ${{ inputs.environment }}"
