name: manual with input
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment Environment"
        required: true
        default: "staging"
jobs:
  input:
    runs-on: ubuntu-latest
    steps:
      - name: Show Environment
        run: echo "deploying to ${{inputs.environment}}"
        
  
