name: multiple variables
on:
  workflow_dispatch:
# job specific variable
env:
  APP_NAME: abhi-app-v2
  ENVIRONMENT: TEST
  AWS_REGION: ap-south-1

jobs:
  multiple-env:
    runs-on: ubuntu-latest
    steps:
      - name: show-env
        run: |
          echo "$APP_NAME"
          echo "$ENVIRONMENT"
          echo "AWS_REGION"
 
  #Step specific variable
  completion:
    runs-on: ubuntu-latest
    steps:
      - name: deploy stage
        env:
          ENVIRONMENT: deploying
        run: echo "$ENVIRONMENT"
      
      - name: complete
        env:
          ENVIRONMENT: completion
        run: |
          echo "$ENVIRONMENT"
          echo "Workflow Completed"
