name: multiple variables
on:
  workflow_dispatch:

env:
  APP_NAME: abhi-app-v2
  ENVIRONMENT: TEST
  AWS_REGION: ap-south-1

jobs:
  multiple-env:
    runs-on: ubuntu-latest
    steps:
      - name: show-env
        run: |
          echo "$APP_NAME"
          echo "$ENVIRONMENT"
          echo "AWS_REGION"
  completion:
    runs-on: ubuntu-latest
    steps:
      - name: complete
        run: echo "Workflow Completed"
